GET http://localhost:3500/api/users

###

GET http://localhost:3500/api/flights/search?destination=City%20B&origin=City%20A&date=2023-05-12T10%3A30%3A00Z&availableSeats=5

###

GET https://greenmiles.onrender.com/api/flights/search?destination=City%20B&origin=City%20A&date=2023-05-12T10%3A30%3A00Z&availableSeats=5


###

POST http://localhost:3500/api/users/login
Content-Type: application/json

{
  "email": "raz@gmail.com",
  "password": "razraz"
}

###
POST http://localhost:3500/api/users/login
Content-Type: application/json

{
  "email": "raz@gmail.com",
  "password": "razraz"
}


###
https://greenmiles.onrender.com/api/flights/search?destinationAirport=CDG&originAirport=ATL&date=2024-08-23&availableSeats=1

###

POST http://localhost:3500/api/flights/booking
Content-Type: application/json

{
    "userId": "64c9dca7e1feda9915eca2b8",
    "flightId": "645e91233fb2fbd063c199c0",
    "price": 450,
    "passengers": 3,
    "dateTime": "2023-09-20T23:21:00.000Z" ,
    "date": "2023-09-20",
    "time": "23:21"
}

###

http://localhost:3500/api/users/64c9db30e1feda9915eca2b7/saved-flights
