GET http://localhost:3500/api/users

###

GET http://localhost:3500/api/flights/search?destination=City%20B&origin=City%20A&date=2023-05-12T10%3A30%3A00Z&availableSeats=5

###

GET https://greenmiles.onrender.com/api/flights/search?destination=City%20B&origin=City%20A&date=2023-05-12T10%3A30%3A00Z&availableSeats=5


###

//Login
POST http://localhost:3500/api/users/login
Content-Type: application/json

{
  "email": "raz@gmail.com",
  "password": "razraz"
}

###
POST https://greenmiles.onrender.com/api/users/login
Content-Type: application/json

{
  "email": "raz@gmail.com",
  "password": "razraz"
}

###

POST https://greenmiles.onrender.com/api/users/register
Content-Type: application/json

{
  "email": "basel@gmail.com",
  "password": "baselbasel",
  "firstName": "basel",
  "lastName": "basel"
}



###
https://greenmiles.onrender.com/api/flights/search?destinationAirport=CDG&originAirport=ATL&date=2024-08-23&availableSeats=1

###

POST http://localhost:3500/api/flights/booking
Content-Type: application/json

{
    "userId": "64c9dca7e1feda9915eca2b8",
    "flightId": "645e91233fb2fbd063c199c0",
    "price": 450,
    "passengers": 3,
    "dateTime": "2023-09-20T23:21:00.000Z" ,
    "date": "2023-09-20",
    "time": "23:21"
}


###

PUT https://greenmiles.onrender.com/api/users/save-hotel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGM5ZGIzMGUxZmVkYTk5MTVlY2EyYjciLCJlbWFpbCI6InJhekBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQ1NjNTMlNJSC5JWFI3MjZBSVhvUlZlRm5kOVF3akU2MWMzN3JBRzdlSVRza0FGbUZiVHBjeSIsInNhdmVkRmxpZ2h0cyI6WyI2NDVlOTEyMzNmYjJmYmQwNjNjMTk5YzAiLCI2NTBkZmYyNmNlMDEyNTk1NjQ3ZDcxYmEiXSwic2F2ZWRIb3RlbHMiOlsiNjQ1ZTkxMjMzZmIyZmJkMDYzYzE5OWJiIiwiNjQ1ZTkxMjMzZmIyZmJkMDYzYzE5OWJjIl0sImZpcnN0TmFtZSI6InJheiIsImxhc3ROYW1lIjoicmF6IiwicGhvbmVOdW1iZXIiOm51bGwsImltYWdlIjpudWxsLCJjb3VudHJ5IjpudWxsLCJjaXR5IjpudWxsLCJhZGRyZXNzIjpudWxsLCJpYXQiOjE2OTU0OTYxMjgsImV4cCI6MTY5NTQ5OTcyOH0.9Elw0kXO9He6kUnSvthTMvAfDGLNx5MCHyr2oymE_DA
Content-Type: application/json

{
  "hotel": {
    "_id": "645e91233fb2fbd063c199bd"
  }
}


###

PUT http://localhost:3500/api/users/unsave-hotel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGM5ZGIzMGUxZmVkYTk5MTVlY2EyYjciLCJlbWFpbCI6InJhekBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQ1NjNTMlNJSC5JWFI3MjZBSVhvUlZlRm5kOVF3akU2MWMzN3JBRzdlSVRza0FGbUZiVHBjeSIsInNhdmVkRmxpZ2h0cyI6WyI2NDVlOTEyMzNmYjJmYmQwNjNjMTk5YzAiLCI2NTBkZmYyNmNlMDEyNTk1NjQ3ZDcxYmEiXSwic2F2ZWRIb3RlbHMiOlsiNjQ1ZTkxMjMzZmIyZmJkMDYzYzE5OWJiIiwiNjQ1ZTkxMjMzZmIyZmJkMDYzYzE5OWJjIl0sImZpcnN0TmFtZSI6InJheiIsImxhc3ROYW1lIjoicmF6IiwicGhvbmVOdW1iZXIiOm51bGwsImltYWdlIjpudWxsLCJjb3VudHJ5IjpudWxsLCJjaXR5IjpudWxsLCJhZGRyZXNzIjpudWxsLCJpYXQiOjE2OTU0OTYxMjgsImV4cCI6MTY5NTQ5OTcyOH0.9Elw0kXO9He6kUnSvthTMvAfDGLNx5MCHyr2oymE_DA
Content-Type: application/json

{
  "hotel": {
    "_id": "645e91233fb2fbd063c199bd"
  }
}

###

PUT https://greenmiles.onrender.com/api/users/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGM5ZGIzMGUxZmVkYTk5MTVlY2EyYjciLCJlbWFpbCI6InJhekBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCRwclYwVUpNdjZjZlovbzdqakNJcXZldHp5N2E2NURuUlN2VVRQNUFtVHAwTTBZL3hKTE9tSyIsInNhdmVkRmxpZ2h0cyI6WyI2NTBkZmYyNmNlMDEyNTk1NjQ3ZDcxYmEiLCI2NDVlOTEyMzNmYjJmYmQwNjNjMTk5YzAiXSwic2F2ZWRIb3RlbHMiOlsiNjQ1ZTkxMjMzZmIyZmJkMDYzYzE5OWJjIl0sImZpcnN0TmFtZSI6InJheiIsImxhc3ROYW1lIjoicmF6IiwicGhvbmVOdW1iZXIiOiIwNTQ1ODQ5MjgxIiwiaW1hZ2UiOm51bGwsImNvdW50cnkiOiIiLCJjaXR5IjoiIiwiYWRkcmVzcyI6IiIsImlhdCI6MTY5NjE3MjYwMywiZXhwIjoxNjk2MTc2MjAzfQ.GLQFJrFSUQolzTAC-vmBFK3_r-ChFc_cJUTRYXDquHA
Content-Type: application/json

{
  "password":  "razraz"
}

###


PUT https://greenmiles.onrender.com/api/users/edit-profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGM5ZGIzMGUxZmVkYTk5MTVlY2EyYjciLCJlbWFpbCI6InJhekBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCRIVUlMRXBpSXdxUTlYaGdsNUI2MWp1YlJmVEw3Mzk3UFd2QTBtZHpCS3p1UXA3Z3VQTzhjTyIsInNhdmVkRmxpZ2h0cyI6WyI2NTBkZmYyNmNlMDEyNTk1NjQ3ZDcxYmEiLCI2NDVlOTEyMzNmYjJmYmQwNjNjMTk5YzAiXSwic2F2ZWRIb3RlbHMiOlsiNjQ1ZTkxMjMzZmIyZmJkMDYzYzE5OWJjIl0sImZpcnN0TmFtZSI6IlJheiIsImxhc3ROYW1lIjoiUmF6IiwicGhvbmVOdW1iZXIiOiIwNTQ1ODQ4NTkyIiwiaW1hZ2UiOm51bGwsImNvdW50cnkiOiJpc3JhZWwiLCJjaXR5IjoiaG9sb24iLCJhZGRyZXNzIjoic29tZXdoZXJlIGluIGhvbG9uIiwiaWF0IjoxNjk2MTIyMDAwLCJleHAiOjE2OTYxMjU2MDB9.DzKXtHesOTruPzfoMwsavGVcDNZm3MPPm3iBDNAIFY8
Content-Type: application/json

{
  "editedUser": {
            "firstName": "Razzy",
            "lastName": "Raz",
            "email": "raz@gmail.com",
            "phoneNumber": "0545848592",
            "country": "israel",
            "city": "holon",
            "address": "somewhere in holon"
  }
}

